version: "3.8"
services:
  bot:
    build: .
    container_name: crypto_telegram_bot
    restart: always
    env_file: .env
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - BINANCE_APIKEY=${BINANCE_APIKEY}
      - BINANCE_APISECRET=${BINANCE_APISECRET}
      - METAMASK_API=${METAMASK_API}
    volumes:
      - .:/app
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
